routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'WebsiteController@index')->name('shop');
Route::get('/artisan-register', 'WebsiteController@artisanRegister')->name('artisan.register');
Route::post('/artisan-request', 'WebsiteController@artisanRequest')->name('artisan.request');

Route::group(['prefix' => 'shop'], function () {
//    Route::get('/man', 'WebsiteController@shopMan')->name('shop.man');
//    Route::get('/woman', 'WebsiteController@shopWoman')->name('shop.woman');
//    Route::get('/woman/accessories', 'WebsiteController@shopProduct')->name('shop.products');

//    Route::get('/woman/product/detail', 'WebsiteController@shopProductDetail')->name('shop.products.detail');
    Route::get('/artisans', 'WebsiteController@shopArtisans')->name('shop.artisans');
    Route::get('/artisans/{slug}', 'WebsiteController@shopArtisansSingle')->name('shop.artisans.single');
    Route::get('/cart', 'WebsiteController@shopCart')->name('shop.cart');
    Route::get('/wish-list', 'WebsiteController@shopWish')->name('shop.wish');
    Route::get('/wishlist/{slug}','WebsiteController@storeWishList')->name('wishlist');
    Route::post('/wishlist-destroy/{id}','WebsiteController@wishListDestroy')->name('destroy');
    Route::get('/about', 'WebsiteController@shopAbout')->name('shop.about');


Route::group(['middleware' => ['auth:web']], function () { 
    Route::get('/checkout', 'WebsiteController@checkout')->name('shop.checkout');
    Route::post('/store-payment', 'PaymentController@paymentStore')->name('store.payment');

});
    // Front Dynamic Route
    Route::get('/{catName}/product/{slug}', 'WebsiteController@productDetails')->name('shop.products.detail');
    Route::get('/{slug}', 'WebsiteController@categoryShop')->name('category.shop');
    Route::get('/{cateName}/{slug}', 'WebsiteController@subcategoryShop');



//    Route::get('/product/{slug}', 'WebsiteController@shopProductDetail');
});


Route::group(['prefix' => 'cart'], function () {
    Route::post('/add/{slug}', 'WebsiteController@addToCart')->name('addToCart');
    Route::post('/update', 'WebsiteController@updateCart')->name('update.cart');
    Route::get('/remove/{id}', 'WebsiteController@removeCart')->name('remove.cart');
    Route::get('/destroy', 'WebsiteController@destroyCart')->name('destroy.cart');

    Route::post('/apply-coupon', 'WebsiteController@applyCoupon')->name('apply.coupon');

});

Route::group(['prefix' => 'user'], function () {
    Route::get('/login', 'WebsiteController@loginPage')->name('user.login.page');
    Route::get('/reset-passwod', 'WebsiteController@resetPage')->name('user.reset');
    Route::get('/customer-support', 'WebsiteController@customerSupport')->name('user.support');
    Route::get('/account', 'WebsiteController@user_accounts')->name('user.accounts.dashboard');

    Route::get('/order', 'WebsiteController@user_order')->name('user.accounts.order');
    Route::get('/order-view/{id}', 'WebsiteController@user_order_view')->name('user.accounts.order.view');

    Route::get('/address', 'WebsiteController@user_address')->name('user.accounts.address');
    Route::get('/accounts-detail', 'WebsiteController@user_details')->name('user.accounts.details');

    Route::post('/user-update/{id}', 'WebsiteController@userUpdate')->name('user.update');
    
    Route::get('/billing-address', 'WebsiteController@user_billing')->name('user.accounts.billing');
    Route::get('/shipping-address', 'WebsiteController@user_shipping')->name('user.accounts.shipping');

    // For Billing Address Routes
    Route::post('/store-billing', 'BillingController@store')->name('store.billing');

    // For shipping Address Routes
    Route::post('/store-shipping', 'ShippingController@store')->name('store.shipping');
});

Route::group(['prefix' => 'legal-area'], function () {
    Route::get('/privacy-policy', 'WebsiteController@privacyPolicy')->name('extra.privacy');
    Route::get('/work-with-us', 'WebsiteController@workWithUs')->name('extra.work');
    Route::get('/terms-and-condition', 'WebsiteController@termsAndConditoin')->name('extra.terms');
    Route::get('/faqs', 'WebsiteController@faqs')->name('extra.faqs');

});

// admin route area
Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'Auth\AdminLogin@showLoginForm');
    Route::post('/login', 'Auth\AdminLogin@login')->name('admin.login');
    Route::post('/cat-wise-subcat/{id}', 'Admin\ProductController@categoryWiseSubcategory');
    Route::get('/product-image/delete/{id}', 'Admin\ProductController@imageDelete');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::post('/logout', 'Auth\AdminLogin@logout')->name('admin.logout');

        Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');

        // for material
        Route::resource('material', 'Admin\MaterialController');
        // for category
        Route::resource('category', 'Admin\CategoryController');
        // for subcategory
        Route::resource('subcategory', 'Admin\SubcategoryController');

        // For Admin Routes
        Route::post('reset-password/{id}', 'Admin\AdminController@resetPassword');
        Route::get('artisan-request', 'Admin\AdminController@artisanRequest')->name('artisan-request');
        Route::get('artisan-accept/{id}', 'Admin\AdminController@artisanAccept');
        Route::get('artisan-reject/{id}', 'Admin\AdminController@artisanReject');
        Route::get('artisan-pending/{id}', 'Admin\AdminController@artisanPending');
        Route::resource('administrator', 'Admin\AdminController');

        // For product Routes
        Route::resource('product', 'Admin\ProductController');

        // For Team Routes
        Route::resource('team', 'Admin\TeamController');

        // For Home Banner Routes
        Route::resource('home-banner', 'Admin\HomeBannerController');

        // For Home Video Routes
        Route::resource('home-video', 'Admin\HomeVideoController');

        // For About Routes
        Route::resource('about', 'Admin\AboutController');

        // For Follow US Routes
        Route::resource('follow-us', 'Admin\FollowUsController');

        // For FAQS Routes
        Route::resource('faq', 'Admin\FaqsController');

        // For Customer Support Routes
        Route::resource('customer-support', 'Admin\CustomerSupportController');

        // For Footer Info Routes
        Route::resource('footer-info', 'Admin\FooterInfoController');

        // For Admin wishlist Routes
        Route::resource('wishlist', 'Admin\WishlistController');

        // For Admin Coupon Routes
        Route::resource('coupon', 'Admin\CouponController');

         // For Admin Order list Routes
         Route::resource('order', 'Admin\OrderController');

        
    });
   

    
    Route::post('/customer-support', 'Admin\CustomerSupportController@store')->name('customer.support');
});

//Route::get('/home', 'HomeController@index')->name('home');
 

resources/views/admin/administrator/create.blade.php
@extends('admin.master')

@section('title')
    Admin / Administrator Create
@endsection

@section('page_title')
    <h2>Create Administrator</h2>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="zmdi zmdi-view-dashboard"></i> Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('administrator.index') }}"><i class="zmdi zmdi-apps"></i> Administrators</a></li>
    <li class="breadcrumb-item active">Administrator Create</li>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-7 col-md-7 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <a href="{{ route('administrator.index') }}" class="btn btn-raised btn-info btn-sm btn-round waves-effect -mt5">
                                <i class="zmdi zmdi-arrow-back"></i> Back
                            </a>
                        </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else</a></li>
                                </ul>
                            </li>
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <form method="post" action="{{ route('administrator.store') }}" enctype="multipart/form-data">
                            @csrf
                            @include('admin.administrator._form')

                            <div class="mb-3">
                                <label for="password">Password<span class="text-danger">*</span></label>
                                <div class="form-group">
                                    <input type="password" id="password" name="password" value="{{ old('password', isset($data->password) ? $data->password:'') }}" class="form-control @error('password') is-invalid @enderror" placeholder=" Password">
                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <label for="password">Confirm Password<span class="text-danger">*</span></label>
                                <div class="form-group">
                                    <input type="password" id="password_confirmation" class="form-control" name="password_confirmation" placeholder=" Confirm Password">
                                    @error('password_confirmation')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <button type="submit" class="btn btn-raised btn-success btn-round waves-effect">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/administrator/edit.blade.php
@extends('admin.master')

@section('title')
    Admin / Administrator Edit
@endsection

@section('page_title')
    <h2>Edit Administrator</h2>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="zmdi zmdi-view-dashboard"></i> Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('administrator.index') }}"><i class="zmdi zmdi-apps"></i> Administrators</a></li>
    <li class="breadcrumb-item active">Administrator Edit</li>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-7 col-md-7 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <a href="{{ route('administrator.index') }}" class="btn btn-raised btn-info btn-sm btn-round waves-effect -mt5">
                                <i class="zmdi zmdi-arrow-back"></i> Back
                            </a>
                        </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else</a></li>
                                </ul>
                            </li>
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <form method="post" action="{{ route('administrator.update', $data->id) }}" enctype="multipart/form-data">
                            @method('PATCH')
                            @csrf
                            @include('admin.administrator._form')
                            <button type="submit" class="btn btn-raised btn-success btn-round waves-effect">Update</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-lg-5 col-md-5 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>Reset Password</h2>
                    </div>
                    <div class="body">
                        <form method="post" action="{{ url('admin/reset-password', $data->id) }}">
                            @csrf
                            <div class="mb-3">
                                <label for="password">Password<span class="text-danger">*</span></label>
                                <div class="form-group">
                                    <input type="password" id="password" name="password" value="{{ old('password') }}" class="form-control @error('password') is-invalid @enderror" placeholder=" Password">
                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="mb-3">
                                <label for="password">Confirm Password<span class="text-danger">*</span></label>
                                <div class="form-group">
                                    <input type="password" id="password_confirmation" class="form-control" name="password_confirmation" placeholder=" Confirm Password">
                                    @error('password_confirmation')
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <button type="submit" class="btn btn-raised btn-success btn-round waves-effect">Submit</button>
                        </form>
                    </div>
                </div>

                @if( $data->avatar)
                    <div class="card">
                        <div class="body">
                            <div id="aniimated-thumbnials" class="list-unstyled row clearfix">
                                <a href="{{ asset('media/admin/'. $data->avatar) }}">
                                    <img class="img-fluid img-thumbnail" src="{{ asset('media/admin/'. $data->avatar) }}" width="300">
                                </a>
                            </div>
                        </div>
                    </div>
                @endif
            </div>


        </div>
    </div>
@endsection
@section('page_js')

@endsection

resources/views/admin/administrator/index.blade.php
@extends('admin.master')

@section('title')
    Admin / Administrators
@endsection

@section('page_title')
    <h2>All Administrator</h2>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="zmdi zmdi-view-dashboard"></i> Dashboard</a></li>
    <li class="breadcrumb-item active">Administrators</li>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <a href="{{ route('administrator.create') }}" class="btn btn-raised btn-info -mt5 btn-sm btn-round waves-effect">
                                <i class="zmdi zmdi-plus-circle"></i> Add New
                            </a>
                        </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                                <ul class="dropdown-menu dropdown-menu-right slideUp float-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else</a></li>
                                </ul>
                            </li>
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                <tr>
                                    <th width="7%">S.NO</th>
                                    <th width="6%">Avatar</th>
                                    <th>Name</th>
                                    <th>Role</th>
                                    <th>Email</th>
                                    <th width="5%">Status</th>
                                    <th width="15%">Action</th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach($data as $key => $administrator)
                                    <tr>
                                        <td>{{ ++$key }}</td>
                                        <td>
                                            @if($administrator->avatar)
                                                <img src="{{ asset('media/admin/'. $administrator->avatar) }}" alt="" width="60">
                                            @endif
                                        </td>
                                        <td>{{ $administrator->name }}</td>
                                        <td>
                                            @if($administrator->role == 'admin')
                                                Admin (Manager)
                                            @else
                                                Craftsman
                                            @endif
                                        </td>
                                        <td>{{ $administrator->email }}</td>
                                        <td>
                                            @if($administrator->status == 'active')
                                                <span class="badge badge-success">Active</span>
                                            @else
                                                <span class="badge badge-danger">Inactive</span>
                                            @endif
                                        </td>
                                        <td class="p-1">

                                            <form action="{{ route('administrator.destroy', $administrator->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <span class="dropdown">
                                                    <a href="javascript:void(0);" class="dropdown-toggle btn btn-default btn-icon btn-simple btn-icon-mini btn-round" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more m-2"></i> </a>
                                                    <ul class="dropdown-menu dropdown-menu-right">
                                                        <li><a href="{{ url('admin/artisan-pending/'. $administrator->id) }}">Pending</a></li>
                                                        <li><a href="{{ url('admin/artisan-reject/'. $administrator->id) }}">Reject</a></li>
                                                    </ul>
                                                </span>
                                                <a href="{!! url('admin/administrator/'.$administrator->id) !!}/edit" class="btn btn-default btn-icon btn-simple btn-icon-mini btn-round">
                                                    <i class="zmdi zmdi-edit m-2"></i>
                                                </a>
                                                <button type="submit" onclick="return confirm('Are you sure...?')" class="btn btn-default btn-icon btn-simple btn-icon-mini btn-round"><i class="zmdi zmdi-delete"></i> </button>
                                            </form>

                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/administrator/request_artisan.blade.php
@extends('admin.master')

@section('title')
    Admin / Artisan Request
@endsection

@section('page_title')
    <h2>All Artisan Request</h2>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="zmdi zmdi-view-dashboard"></i> Dashboard</a></li>
    <li class="breadcrumb-item active">Artisan Requests</li>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2>Artisan Requests List</h2>
                        <ul class="header-dropdown">
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                <tr>
                                    <th width="7%">S.NO</th>
                                    <th width="6%">Avatar</th>
                                    <th>Name</th>
                                    <th>Role</th>
                                    <th>Email</th>
                                    <th width="5%">Request</th>
                                    <th width="15%">Action</th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach($data as $key => $administrator)
                                    <tr>
                                        <td>{{ ++$key }}</td>
                                        <td>
                                            @if($administrator->avatar)
                                                <img src="{{ asset('media/admin/'. $administrator->avatar) }}" alt="" width="50">
                                            @endif
                                        </td>
                                        <td>{{ $administrator->name }}</td>
                                        <td>
                                            @if($administrator->role == 'admin')
                                                Admin (Manager)
                                            @else
                                                Craftsman
                                            @endif
                                        </td>
                                        <td>{{ $administrator->email }}</td>
                                        <td>
                                            @if($administrator->craft_request == 'accept')
                                                <span class="badge badge-success">Accept</span>
                                            @elseif($administrator->craft_request == 'pending')
                                                <span class="badge badge-warning">Pending</span>
                                            @else
                                                <span class="badge badge-danger">Reject</span>
                                            @endif
                                        </td>
                                        <td class="p-1">

                                            <form action="{{ route('administrator.destroy', $administrator->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <span class="dropdown">
                                                    <a href="javascript:void(0);" class="dropdown-toggle btn btn-default btn-icon btn-simple btn-icon-mini btn-round" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more m-2"></i> </a>
                                                    <ul class="dropdown-menu dropdown-menu-right">
                                                        <li><a href="{{ url('admin/artisan-accept/'. $administrator->id) }}">Accept</a></li>
                                                        <li><a href="{{ url('admin/artisan-reject/'. $administrator->id) }}">Reject</a></li>
                                                    </ul>
                                                </span>
                                                <a href="{!! url('admin/administrator/'.$administrator->id) !!}/edit" class="btn btn-default btn-icon btn-simple btn-icon-mini btn-round">
                                                    <i class="zmdi zmdi-edit m-2"></i>
                                                </a>
                                                <button type="submit" onclick="return confirm('Are you sure...?')" class="btn btn-default btn-icon btn-simple btn-icon-mini btn-round"><i class="zmdi zmdi-delete"></i> </button>

                                            </form>

                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection