routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'WebsiteController@index')->name('shop');
Route::get('/artisan-register', 'WebsiteController@artisanRegister')->name('artisan.register');
Route::post('/artisan-request', 'WebsiteController@artisanRequest')->name('artisan.request');

Route::group(['prefix' => 'shop'], function () {
//    Route::get('/man', 'WebsiteController@shopMan')->name('shop.man');
//    Route::get('/woman', 'WebsiteController@shopWoman')->name('shop.woman');
//    Route::get('/woman/accessories', 'WebsiteController@shopProduct')->name('shop.products');

//    Route::get('/woman/product/detail', 'WebsiteController@shopProductDetail')->name('shop.products.detail');
    Route::get('/artisans', 'WebsiteController@shopArtisans')->name('shop.artisans');
    Route::get('/artisans/{slug}', 'WebsiteController@shopArtisansSingle')->name('shop.artisans.single');
    Route::get('/cart', 'WebsiteController@shopCart')->name('shop.cart');
    Route::get('/wish-list', 'WebsiteController@shopWish')->name('shop.wish');
    Route::get('/wishlist/{slug}','WebsiteController@storeWishList')->name('wishlist');
    Route::post('/wishlist-destroy/{id}','WebsiteController@wishListDestroy')->name('destroy');
    Route::get('/about', 'WebsiteController@shopAbout')->name('shop.about');


Route::group(['middleware' => ['auth:web']], function () { 
    Route::get('/checkout', 'WebsiteController@checkout')->name('shop.checkout');
    Route::post('/store-payment', 'PaymentController@paymentStore')->name('store.payment');

});
    // Front Dynamic Route
    Route::get('/{catName}/product/{slug}', 'WebsiteController@productDetails')->name('shop.products.detail');
    Route::get('/{slug}', 'WebsiteController@categoryShop')->name('category.shop');
    Route::get('/{cateName}/{slug}', 'WebsiteController@subcategoryShop');



//    Route::get('/product/{slug}', 'WebsiteController@shopProductDetail');
});


Route::group(['prefix' => 'cart'], function () {
    Route::post('/add/{slug}', 'WebsiteController@addToCart')->name('addToCart');
    Route::post('/update', 'WebsiteController@updateCart')->name('update.cart');
    Route::get('/remove/{id}', 'WebsiteController@removeCart')->name('remove.cart');
    Route::get('/destroy', 'WebsiteController@destroyCart')->name('destroy.cart');

    Route::post('/apply-coupon', 'WebsiteController@applyCoupon')->name('apply.coupon');

});

Route::group(['prefix' => 'user'], function () {
    Route::get('/login', 'WebsiteController@loginPage')->name('user.login.page');
    Route::get('/reset-passwod', 'WebsiteController@resetPage')->name('user.reset');
    Route::get('/customer-support', 'WebsiteController@customerSupport')->name('user.support');
    Route::get('/account', 'WebsiteController@user_accounts')->name('user.accounts.dashboard');

    Route::get('/order', 'WebsiteController@user_order')->name('user.accounts.order');
    Route::get('/order-view/{id}', 'WebsiteController@user_order_view')->name('user.accounts.order.view');

    Route::get('/address', 'WebsiteController@user_address')->name('user.accounts.address');
    Route::get('/accounts-detail', 'WebsiteController@user_details')->name('user.accounts.details');

    Route::post('/user-update/{id}', 'WebsiteController@userUpdate')->name('user.update');
    
    Route::get('/billing-address', 'WebsiteController@user_billing')->name('user.accounts.billing');
    Route::get('/shipping-address', 'WebsiteController@user_shipping')->name('user.accounts.shipping');

    // For Billing Address Routes
    Route::post('/store-billing', 'BillingController@store')->name('store.billing');

    // For shipping Address Routes
    Route::post('/store-shipping', 'ShippingController@store')->name('store.shipping');
});

Route::group(['prefix' => 'legal-area'], function () {
    Route::get('/privacy-policy', 'WebsiteController@privacyPolicy')->name('extra.privacy');
    Route::get('/work-with-us', 'WebsiteController@workWithUs')->name('extra.work');
    Route::get('/terms-and-condition', 'WebsiteController@termsAndConditoin')->name('extra.terms');
    Route::get('/faqs', 'WebsiteController@faqs')->name('extra.faqs');

});

// admin route area
Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'Auth\AdminLogin@showLoginForm');
    Route::post('/login', 'Auth\AdminLogin@login')->name('admin.login');
    Route::post('/cat-wise-subcat/{id}', 'Admin\ProductController@categoryWiseSubcategory');
    Route::get('/product-image/delete/{id}', 'Admin\ProductController@imageDelete');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::post('/logout', 'Auth\AdminLogin@logout')->name('admin.logout');

        Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');

        // for material
        Route::resource('material', 'Admin\MaterialController');
        // for category
        Route::resource('category', 'Admin\CategoryController');
        // for subcategory
        Route::resource('subcategory', 'Admin\SubcategoryController');

        // For Admin Routes
        Route::post('reset-password/{id}', 'Admin\AdminController@resetPassword');
        Route::get('artisan-request', 'Admin\AdminController@artisanRequest')->name('artisan-request');
        Route::get('artisan-accept/{id}', 'Admin\AdminController@artisanAccept');
        Route::get('artisan-reject/{id}', 'Admin\AdminController@artisanReject');
        Route::get('artisan-pending/{id}', 'Admin\AdminController@artisanPending');
        Route::resource('administrator', 'Admin\AdminController');

        // For product Routes
        Route::resource('product', 'Admin\ProductController');

        // For Team Routes
        Route::resource('team', 'Admin\TeamController');

        // For Home Banner Routes
        Route::resource('home-banner', 'Admin\HomeBannerController');

        // For Home Video Routes
        Route::resource('home-video', 'Admin\HomeVideoController');

        // For About Routes
        Route::resource('about', 'Admin\AboutController');

        // For Follow US Routes
        Route::resource('follow-us', 'Admin\FollowUsController');

        // For FAQS Routes
        Route::resource('faq', 'Admin\FaqsController');

        // For Customer Support Routes
        Route::resource('customer-support', 'Admin\CustomerSupportController');

        // For Footer Info Routes
        Route::resource('footer-info', 'Admin\FooterInfoController');

        // For Admin wishlist Routes
        Route::resource('wishlist', 'Admin\WishlistController');

        // For Admin Coupon Routes
        Route::resource('coupon', 'Admin\CouponController');

         // For Admin Order list Routes
         Route::resource('order', 'Admin\OrderController');

        
    });
   

    
    Route::post('/customer-support', 'Admin\CustomerSupportController@store')->name('customer.support');
});

//Route::get('/home', 'HomeController@index')->name('home');
 

app/Models/FollowUs.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class FollowUs extends Model
{
    protected $fillable = ['social_media_name', 'social_media_link', 'status'];
}

app/Http/Controllers/Admin/FollowUsController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Models\FollowUs;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Validator;


class FollowUsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = FollowUs::get();
        return  view('admin.follow-us.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = null;
        return  view('admin.follow-us.create', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'social_media_name' => 'required|max:255',
            'social_media_link' => 'required|url',
            'status' => Rule::in(['active', 'inactive']),
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        
        FollowUs::create($data);
        return  redirect()->back()->with('success', 'Follow US save successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = FollowUs::find($id);
        return  view('admin.follow-us.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'social_media_name' => 'required|max:255',
            'social_media_link' => 'required|url',
            'status' => Rule::in(['active', 'inactive']),
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        FollowUs::find($id)->update($data);
        return  redirect()->back()->with('success', 'Follow Us update successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = FollowUs::find($id);
        $data->delete();
        return redirect()->back()->with('success', 'Follow Us deleted');
    }
}

resources/views/admin/follow-us/_form.blade.php
<div class="mb-3">
    <label for="social_media_name">Social Media Name <span class="text-danger">*</span></label>
    <div class="form-group">
        <input type="text" id="social_media_name" name="social_media_name" value="{{ old('social_media_name', isset($data->social_media_name) ? $data->social_media_name:'') }}" class="form-control @error('social_media_name') is-invalid @enderror" placeholder="Social media name">
        @error('social_media_name')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>

<div class="mb-3">
    <label for="social_media_link">Social Media Link</label>
    <div class="form-group">
        <textarea  id="social_media_link" name="social_media_link" class="form-control @error('social_media_link') is-invalid @enderror" placeholder="Category social_media_link">{{ old('social_media_link', isset($data->social_media_link) ? $data->social_media_link:'') }}</textarea>
        @error('Social_media_link')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
</div>


<div class="mb-3">
<div class="form-group">
    <div class="radio inlineblock m-r-20">
        <input type="radio" name="status" id="active" class="with-gap" value="active" {{ isset($data->status) && $data->status == 'active' ? 'checked':'' }}>
        <label for="active">Active</label>
    </div>
    <div class="radio inlineblock">
        <input type="radio" name="status" id="inactive" class="with-gap" value="inactive" {{ isset($data->status) && $data->status == 'inactive' ? 'checked':'' }}>
        <label for="inactive">Inactive</label>
    </div>
    @error('status')
    <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
    @enderror
</div>
</div>

resources/views/admin/follow-us/create.blade.php
@extends('admin.master')

@section('title')
    Admin /Follow US Create
@endsection

@section('page_title')
    <h2>Create Follow US</h2>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="zmdi zmdi-view-dashboard"></i> Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('follow-us.index') }}"><i class="zmdi zmdi-apps"></i> Follow Us</a></li>
    <li class="breadcrumb-item active">Follow Us</li>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-7 col-md-7 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <a href="{{ route('follow-us.index') }}" class="btn btn-raised btn-info btn-sm btn-round waves-effect -mt5">
                                <i class="zmdi zmdi-arrow-back"></i> Back
                            </a>
                        </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else</a></li>
                                </ul>
                            </li>
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <form method="post" action="{{ route('follow-us.store') }}" enctype="multipart/form-data">
                            @csrf
                            @include('admin.follow-us._form')
                            <button type="submit" class="btn btn-raised btn-success btn-round waves-effect">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/follow-us/edit.blade.php
@extends('admin.master')

@section('title')
    Admin / Follow Us Edit
@endsection

@section('page_title')
    <h2>Edit Follow Us</h2>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="zmdi zmdi-view-dashboard"></i> Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('follow-us.index') }}"><i class="zmdi zmdi-apps"></i> Follow Us</a></li>
    <li class="breadcrumb-item active">Follow Us</li>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-7 col-md-7 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <a href="{{ route('follow-us.index') }}" class="btn btn-raised btn-info btn-sm btn-round waves-effect -mt5">
                                <i class="zmdi zmdi-arrow-back"></i> Back
                            </a>
                        </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else</a></li>
                                </ul>
                            </li>
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <form method="post" action="{{ route('follow-us.update', $data->id) }}" enctype="multipart/form-data">
                            @method('PATCH')
                            @csrf
                            @include('admin.follow-us._form')
                            <button type="submit" class="btn btn-raised btn-success btn-round waves-effect">Update</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/follow-us/index.blade.php
@extends('admin.master')

@section('title')
    Admin / Follow Us
@endsection

@section('page_title')
    <h2>All Follow Us</h2>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="zmdi zmdi-view-dashboard"></i> Dashboard</a></li>
    <li class="breadcrumb-item active">Follow Us</li>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <a href="{{ route('follow-us.create') }}" class="btn btn-raised btn-info -mt5 btn-sm btn-round waves-effect">
                                <i class="zmdi zmdi-plus-circle"></i> Add New
                            </a>
                        </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                                <ul class="dropdown-menu dropdown-menu-right slideUp float-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else</a></li>
                                </ul>
                            </li>
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                            <thead>
                            <tr>
                                <th width="10%">S.NO</th>
                                <th>Social Media Name</th>
                                <th>Social Media Link</th>
                                <th width="5%">Status</th>
                                <th width="15%">Action</th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach($data as $key => $follow)
                            <tr>
                                <td>{{ ++$key }}</td>
                                
                                <td>{{ $follow->social_media_name }}</td>
                                <td><a href="{{ $follow->social_media_link }}" target="_blank">{{ $follow->social_media_link }}</a></td>
                                <td>
                                    @if($follow->status == 'active')
                                        <span class="badge badge-success">Active</span>
                                    @else
                                        <span class="badge badge-danger">Inactive</span>
                                    @endif
                                </td>
                                <td class="p-1">

                                    <form action="{{ route('follow-us.destroy', $follow->id)}}" method="post">
                                        @csrf
                                        @method('DELETE')

                                        <a href="{!! url('admin/follow-us/'.$follow->id) !!}/edit" class="btn btn-default btn-icon btn-simple btn-icon-mini btn-round"><i class="zmdi zmdi-edit m-2"></i></a>
                                        <button type="submit" onclick="return confirm('Are you sure...?')"  class="btn btn-default btn-icon btn-simple btn-icon-mini btn-round"><i class="zmdi zmdi-delete"></i></button>
                                    </form>

                                </td>
                            </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection