routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'WebsiteController@index')->name('shop');
Route::get('/artisan-register', 'WebsiteController@artisanRegister')->name('artisan.register');
Route::post('/artisan-request', 'WebsiteController@artisanRequest')->name('artisan.request');

Route::group(['prefix' => 'shop'], function () {
//    Route::get('/man', 'WebsiteController@shopMan')->name('shop.man');
//    Route::get('/woman', 'WebsiteController@shopWoman')->name('shop.woman');
//    Route::get('/woman/accessories', 'WebsiteController@shopProduct')->name('shop.products');

//    Route::get('/woman/product/detail', 'WebsiteController@shopProductDetail')->name('shop.products.detail');
    Route::get('/artisans', 'WebsiteController@shopArtisans')->name('shop.artisans');
    Route::get('/artisans/{slug}', 'WebsiteController@shopArtisansSingle')->name('shop.artisans.single');
    Route::get('/cart', 'WebsiteController@shopCart')->name('shop.cart');
    Route::get('/wish-list', 'WebsiteController@shopWish')->name('shop.wish');
    Route::get('/wishlist/{slug}','WebsiteController@storeWishList')->name('wishlist');
    Route::post('/wishlist-destroy/{id}','WebsiteController@wishListDestroy')->name('destroy');
    Route::get('/about', 'WebsiteController@shopAbout')->name('shop.about');


Route::group(['middleware' => ['auth:web']], function () { 
    Route::get('/checkout', 'WebsiteController@checkout')->name('shop.checkout');
    Route::post('/store-payment', 'PaymentController@paymentStore')->name('store.payment');

});
    // Front Dynamic Route
    Route::get('/{catName}/product/{slug}', 'WebsiteController@productDetails')->name('shop.products.detail');
    Route::get('/{slug}', 'WebsiteController@categoryShop')->name('category.shop');
    Route::get('/{cateName}/{slug}', 'WebsiteController@subcategoryShop');



//    Route::get('/product/{slug}', 'WebsiteController@shopProductDetail');
});


Route::group(['prefix' => 'cart'], function () {
    Route::post('/add/{slug}', 'WebsiteController@addToCart')->name('addToCart');
    Route::post('/update', 'WebsiteController@updateCart')->name('update.cart');
    Route::get('/remove/{id}', 'WebsiteController@removeCart')->name('remove.cart');
    Route::get('/destroy', 'WebsiteController@destroyCart')->name('destroy.cart');

    Route::post('/apply-coupon', 'WebsiteController@applyCoupon')->name('apply.coupon');

});

Route::group(['prefix' => 'user'], function () {
    Route::get('/login', 'WebsiteController@loginPage')->name('user.login.page');
    Route::get('/reset-passwod', 'WebsiteController@resetPage')->name('user.reset');
    Route::get('/customer-support', 'WebsiteController@customerSupport')->name('user.support');
    Route::get('/account', 'WebsiteController@user_accounts')->name('user.accounts.dashboard');

    Route::get('/order', 'WebsiteController@user_order')->name('user.accounts.order');
    Route::get('/order-view/{id}', 'WebsiteController@user_order_view')->name('user.accounts.order.view');

    Route::get('/address', 'WebsiteController@user_address')->name('user.accounts.address');
    Route::get('/accounts-detail', 'WebsiteController@user_details')->name('user.accounts.details');

    Route::post('/user-update/{id}', 'WebsiteController@userUpdate')->name('user.update');
    
    Route::get('/billing-address', 'WebsiteController@user_billing')->name('user.accounts.billing');
    Route::get('/shipping-address', 'WebsiteController@user_shipping')->name('user.accounts.shipping');

    // For Billing Address Routes
    Route::post('/store-billing', 'BillingController@store')->name('store.billing');

    // For shipping Address Routes
    Route::post('/store-shipping', 'ShippingController@store')->name('store.shipping');
});

Route::group(['prefix' => 'legal-area'], function () {
    Route::get('/privacy-policy', 'WebsiteController@privacyPolicy')->name('extra.privacy');
    Route::get('/work-with-us', 'WebsiteController@workWithUs')->name('extra.work');
    Route::get('/terms-and-condition', 'WebsiteController@termsAndConditoin')->name('extra.terms');
    Route::get('/faqs', 'WebsiteController@faqs')->name('extra.faqs');

});

// admin route area
Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'Auth\AdminLogin@showLoginForm');
    Route::post('/login', 'Auth\AdminLogin@login')->name('admin.login');
    Route::post('/cat-wise-subcat/{id}', 'Admin\ProductController@categoryWiseSubcategory');
    Route::get('/product-image/delete/{id}', 'Admin\ProductController@imageDelete');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::post('/logout', 'Auth\AdminLogin@logout')->name('admin.logout');

        Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');

        // for material
        Route::resource('material', 'Admin\MaterialController');
        // for category
        Route::resource('category', 'Admin\CategoryController');
        // for subcategory
        Route::resource('subcategory', 'Admin\SubcategoryController');

        // For Admin Routes
        Route::post('reset-password/{id}', 'Admin\AdminController@resetPassword');
        Route::get('artisan-request', 'Admin\AdminController@artisanRequest')->name('artisan-request');
        Route::get('artisan-accept/{id}', 'Admin\AdminController@artisanAccept');
        Route::get('artisan-reject/{id}', 'Admin\AdminController@artisanReject');
        Route::get('artisan-pending/{id}', 'Admin\AdminController@artisanPending');
        Route::resource('administrator', 'Admin\AdminController');

        // For product Routes
        Route::resource('product', 'Admin\ProductController');

        // For Team Routes
        Route::resource('team', 'Admin\TeamController');

        // For Home Banner Routes
        Route::resource('home-banner', 'Admin\HomeBannerController');

        // For Home Video Routes
        Route::resource('home-video', 'Admin\HomeVideoController');

        // For About Routes
        Route::resource('about', 'Admin\AboutController');

        // For Follow US Routes
        Route::resource('follow-us', 'Admin\FollowUsController');

        // For FAQS Routes
        Route::resource('faq', 'Admin\FaqsController');

        // For Customer Support Routes
        Route::resource('customer-support', 'Admin\CustomerSupportController');

        // For Footer Info Routes
        Route::resource('footer-info', 'Admin\FooterInfoController');

        // For Admin wishlist Routes
        Route::resource('wishlist', 'Admin\WishlistController');

        // For Admin Coupon Routes
        Route::resource('coupon', 'Admin\CouponController');

         // For Admin Order list Routes
         Route::resource('order', 'Admin\OrderController');

        
    });
   

    
    Route::post('/customer-support', 'Admin\CustomerSupportController@store')->name('customer.support');
});

//Route::get('/home', 'HomeController@index')->name('home');
 

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\Models\Material;
use App\Models\Product;
use App\Models\User;
use App\Models\ProductColor;
use App\Models\ProductImage;
use App\Models\ProductShippingReturn;
use App\Models\ProductSize;
use App\Models\Subcategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Validator;
use Auth;
class ProductController extends Controller
{

    public $_moduleImagePath;
    public function __construct()
    {
        $this->_moduleImagePath = 'product/';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Product::orderBy('id', 'desc')->paginate(15);
        return  view('admin.product.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = null;
        $categories = Category::where('status', 'active')->get();
        $subcategories = Subcategory::where('status', 'active')->get();
        $materials = Material::where('status', 'active')->get();
        return  view('admin.product.create', compact('data', 'categories', 'subcategories', 'materials'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $admin =  auth()->guard('admin')->user();

        $data = $request->all();

        $validator = Validator::make($data, [
            'category_id'     => 'required|numeric',
            'subcategory_id'  => 'required|numeric',
            'name'            => 'required|max:255',
            'code'            => 'required|max:255',
            'price'           => 'required|regex:/^\d+(\.\d{1,2})?$/',
            'description'     => 'required',
            'thum_image_1'    => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            'status'          => 'required',
            'in_stock'        => 'required|numeric',
        ],[
            'category_id.required'    => 'Please select a category',
            'category_id.numeric'     => 'Please select a category',
            'subcategory_id.required' => 'Please select a subcategory',
            'subcategory_id.numeric'  => 'Please select a subcategory',
            'in_stock.required'       => 'The stock field is required.',
            'in_stock.numeric'        => 'Please insert number value (1 to 100...)',
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        if($request->hasFile('thum_image_1')) {
            $fileName =  imageUpload($request->file('thum_image_1'), "thum1_$request->name", $this->_moduleImagePath.'/thum/', '400', '400');
            $data['thum_image_1'] = $fileName;
        }
        if($request->hasFile('thum_image_2')) {
            $fileName =  imageUpload($request->file('thum_image_2'), "thum2_$request->name" , $this->_moduleImagePath.'/thum/', '400', '400');
            $data['thum_image_2'] = $fileName;
        }
        $data['admin_id'] = $admin->id;

        if($admin->role == 'craftsman'){
            $data['craftsman_id'] = $admin->id;
        }
        
        $productData = Product::create($data);
        if ($productData->id){
            // ########### After Product Insert ##############
            if (isset($data['check_color'])){
                if (!empty($data['product_color'])) {
                    //array filter for zero empty value check
                    $productColors = $data['product_color'];
                    $productColors = !empty($productColors) ? array_values(array_filter($productColors)) : array();
                    $colorData = [];
                    foreach ($productColors as $k => $color) {
                        $colorData[] = [
                            'product_id'   => $productData->id, // Product ID
                            'colors' => $color,
                        ];
                    }
                    if (!empty($colorData)) {
                        ProductColor::insert($colorData);
                    }else{
                        return redirect()->back()->with('error', 'Product color insert failed!');
                    }
                }
            }

            if (isset($data['check_size'])){
                if (!empty($data['product_size'])) {
                    //array filter for zero empty value check
                    $productSizes = $data['product_size'];
                    $productSizes = !empty($productSizes) ? array_values(array_filter($productSizes)) : array();
                    $sizeData = [];
                    foreach ($productSizes as $k => $size) {
                        $sizeData[] = [
                            'product_id'   => $productData->id, // Product ID
                            'size' => $size,
                        ];
                    }
                    if (!empty($sizeData)) {
                        ProductSize::insert($sizeData);
                    }else{
                        return redirect()->back()->with('error', 'Product size insert failed!');
                    }
                }
            }

            if (isset($data['check_image'])){
                if ($request->hasFile('product_image')) {
                    $images = [];
                    foreach($request->file('product_image') as $key => $image)
                    {
                        $fileNameMt =  imageUpload($image, "_$request->name", "$this->_moduleImagePath", '1200', '1200');
                        $images[] = [
                            'product_id' => $productData->id,
                            'image' => $fileNameMt,
                        ];
                    }
                    if (!empty($images)) {
                        ProductImage::insert($images);
                    }
                }
            }

            if (isset($data['check_shipping_return'])){
                $shipping = new ProductShippingReturn();
                $shipping->product_id        = $productData->id;
                $shipping->shipping_ue       = $data['shipping_ue'];
                $shipping->shipping_extra_ue = $data['shipping_extra_ue'];
                $shipping->delivery_time     = $data['delivery_time'];
                $shipping->return_policy     = $data['return_policy'];
                $shipping->save();
            }
            return redirect()->back()->with('success', 'Product save successfully!');
        }else{
            return redirect()->back()->with('error', 'Product insert failed!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Product::with('ShippingReturn')->find($id);
        return view('admin.product.view', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data          = Product::with('ShippingReturn')->find($id);
        $materials     = Material::where('status', 'active')->get();
        $categories    = Category::where('status', 'active')->get();
        $subcategories = Category::where('id', $data->category_id)->with('subcategories')->first();
        return  view('admin.product.edit', compact('data', 'categories', 'subcategories', 'materials'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'category_id'    => 'required|numeric',
            'material_id'    => 'required|numeric',
            'subcategory_id' => 'required|numeric',
            'name'           => 'required|max:255',
            'title'          => 'required|max:255',
            'code'           => 'required|max:255',
            'price'          => 'required|regex:/^\d+(\.\d{1,2})?$/',
            'description'    => 'required',
            'thum_image_1'   => 'sometimes|image|mimes:jpeg,png,jpg,gif,svg',
            'status'         => 'required',
            'in_stock'       => 'required|numeric',
        ],[
            'material.required'       => 'Please select a material',
            'category_id.required'    => 'Please select a category',
            'category_id.numeric'     => 'Please select a category',
            'subcategory_id.required' => 'Please select a subcategory',
            'subcategory_id.numeric'  => 'Please select a subcategory',
            'in_stock.required'       => 'The stock field is required.',
            'in_stock.numeric'        => 'Please insert number value (1 to 100...)',
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        if($request->hasFile('thum_image_1')) {
            $checkImg = Product::find($id);
            if ($checkImg->thum_image_1){
                if (!file_exists(public_path('media/'.$this->_moduleImagePath.'thum/'.$checkImg->thum_image_1))){
                    $checkImg->thum_image_1 = null;
                }else{
                    imageUnlink($checkImg->thum_image_1, $this->_moduleImagePath.'thum/');
                }
            }
            $fileName =  imageUpload($request->file('thum_image_1'), "thum1_$request->name", $this->_moduleImagePath.'/thum/', '400', '400');

resources/views/admin/product/_form.blade.php
<div class="card">
    <div class="header">
        <h2>
            <a href="{{ route('category.index') }}" class="btn btn-raised btn-info btn-sm btn-round waves-effect -mt5">
                <i class="zmdi zmdi-arrow-back"></i> Back
            </a>
        </h2>
        <ul class="header-dropdown">
            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="javascript:void(0);">Action</a></li>
                    <li><a href="javascript:void(0);">Another action</a></li>
                    <li><a href="javascript:void(0);">Something else</a></li>
                </ul>
            </li>
            <li class="remove">
                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
            </li>
        </ul>
    </div>

    <div class="body">
        <div class="mb-3">
            <label for="title">Category Title <span class="text-danger">*</span></label>
            <div class="form-group">
                <input type="text" id="title" name="title" value="{{ old('title', isset($data->title) ? $data->title:'') }}" class="form-control @error('title') is-invalid @enderror" placeholder="Category Title">
                @error('title')
                <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
                @enderror
            </div>
        </div>

        <div class="mb-3">
            <label for="description">Category Description</label>
            <div class="form-group">
                <textarea  id="description" name="description" class="form-control @error('description') is-invalid @enderror" placeholder="Category Description">{{ old('description', isset($data->description) ? $data->description:'') }}</textarea>
                @error('description')
                <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
                @enderror
            </div>
        </div>

        <div class="mb-3">
            <label>Image <small class="text-danger">[Size: (800x800)]</small></label>
            <div class="form-group">
                <input type="file" id="image" name="image" accept="image/*" class="form-control @error('image') is-invalid @enderror" >
                @error('image')
                <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
                @enderror
            </div>
        </div>

        <div class="mb-3">
            <div class="form-group">
                <div class="radio inlineblock m-r-20">
                    <input type="radio" name="status" id="active" class="with-gap" value="active" {{ isset($data->status) && $data->status == 'active' ? 'checked':'' }}>
                    <label for="active">Active</label>
                </div>
                <div class="radio inlineblock">
                    <input type="radio" name="status" id="inactive" class="with-gap" value="inactive" {{ isset($data->status) && $data->status == 'inactive' ? 'checked':'' }}>
                    <label for="inactive">Inactive</label>
                </div>
                @error('status')
                <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
                @enderror
            </div>
        </div>
    </div>
</div>

resources/views/admin/product/create.blade.php
@extends('admin.master')

@section('title')
    Admin / Product Create
@endsection

@section('page_title')
    <h2>Create Product</h2>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="zmdi zmdi-view-dashboard"></i> Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('product.index') }}"><i class="zmdi zmdi-apps"></i> Products</a></li>
    <li class="breadcrumb-item active">Create Product</li>
@endsection

@section('content')
    <div class="container-fluid">
        <form method="post" action="{{ route('product.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="row clearfix">
                <div class="col-lg-7 col-md-7 col-sm-12">
                    @include('admin.product._form_main')
                </div>

                <div class="col-lg-5 col-md-5 col-sm-12">
                    @include('admin.product._form_color')
                    @include('admin.product._form_size')
                    @include('admin.product._form_image')
                    @include('admin.product._form_shipping_returns')
                </div>
            </div>

            <input type="submit" class="btn btn-raised btn-success btn-round waves-effect" value="Submit">
        </form>
    </div>
@endsection

@section('page_js')
    <script src="{{ asset('admin') }}/plugins/ckeditor/custom.js"></script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.master')

@section('title')
    Admin / Product Edit / {{ $data->name }}
@endsection

@section('page_title')
    <h2>Edit Product</h2>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="zmdi zmdi-view-dashboard"></i> Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{ route('product.index') }}"><i class="zmdi zmdi-apps"></i> Products</a></li>
    <li class="breadcrumb-item active">Edit</li>
@endsection

@section('content')

    <div class="container-fluid">
        <form method="post" action="{{ route('product.update', $data->id) }}" enctype="multipart/form-data">
            @method('PATCH')
            @csrf
            <div class="row clearfix">
                <div class="col-lg-7 col-md-7 col-sm-12">
                    @include('admin.product._form_main')
                </div>

                <div class="col-lg-5 col-md-5 col-sm-12">
                    @include('admin.product._form_color')
                    @include('admin.product._form_size')
                    @include('admin.product._form_image')
                    @include('admin.product._form_shipping_returns')
                </div>
            </div>

            <input type="submit" class="btn btn-raised btn-success btn-round waves-effect" value="Update">
        </form>
    </div>
@endsection

@section('page_js')
    <script src="{{ asset('admin') }}/plugins/ckeditor/custom.js"></script>
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.master')

@section('title')
    Admin / Products
@endsection

@section('page_title')
    <h2>All Products</h2>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}"><i class="zmdi zmdi-view-dashboard"></i> Dashboard</a></li>
    <li class="breadcrumb-item active">Products</li>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="container-fluid">
            <div class="row clearfix">
                <div class="col-lg-12">
                    <div class="card product_item_list">
                        <div class="header">
                            <h2>
                                <a href="{{ route('product.create') }}" class="btn btn-raised btn-info -mt5 btn-sm btn-round waves-effect">
                                    <i class="zmdi zmdi-plus-circle"></i> Add New
                                </a>
                            </h2>
                            <ul class="header-dropdown">
                                <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                                    <ul class="dropdown-menu dropdown-menu-right slideUp float-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else</a></li>
                                    </ul>
                                </li>
                                <li class="remove">
                                    <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                                </li>
                            </ul>
                        </div>
                        <div class="body table-responsive">
                            <table class="table table-hover m-b-0">
                                <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Categories/Material</th>
                                    <th data-breakpoints="sm xs">Detail</th>
                                    <th data-breakpoints="xs">Amount</th>
                                    <th data-breakpoints="xs md">Stock</th>
                                    <th data-breakpoints="xs md">Status</th>
                                    <th data-breakpoints="sm xs md">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($data as $product)
                                <tr>
                                    <td>
                                        @if($product->thum_image_1)
                                            <img src="{{ asset('media/product/thum/'. $product->thum_image_1) }}" width="48" alt="{{ $product->name }}">
                                        @endif
                                    </td>
                                    <td>
                                        @if($product->craftsman_id)
                                            <h5>{{ $product->craftsman->name }}</h5>
                                        @endif
                                        <h5>{{ $product->name }}</h5>
                                    </td>
                                    <td>
                                        @if(!empty($product->material->title))
                                         <h5><strong>Material: </strong>{{ $product->material->title }}</h5>
                                        @endif
                                         <h5><strong>Category: </strong>{{ $product->category->title }}</h5>
                                         <h5><strong>Subcategory: </strong>{{ $product->subcategory->title }}</h5>
                                    </td>
                                    <td><span class="text-muted">{!! substr($product->description, 0, 50) !!}</span></td>
                                    <td>${{ $product->price }}</td>
                                    <td>
                                        @if($product->in_stock > 20)
                                            <span class="col-green">In Stock ({{ $product->in_stock }})</span>
                                        @elseif($product->in_stock > 0 && $product->in_stock < 20)
                                            <span class="col-amber">Low Stock ({{ $product->in_stock }})</span>
                                        @elseif($product->in_stock == 0)
                                            <span class="col-red">Out Of Stock</span>
                                        @endif
                                    </td>
                                    <td>
                                        @if($product->status == 'active')
                                            <span class="badge badge-success">Active</span>
                                        @else
                                            <span class="badge badge-danger">Inactive</span>
                                        @endif
                                    </td>
                                    <td>
                                        <form action="{{ route('product.destroy', $product->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ url('admin/product/'. $product->id) }}" class="btn btn-default waves-effect waves-float waves-green"><i class="zmdi zmdi-eye"></i></a>
                                            <a href="{{ url('admin/product/'. $product->id) }}/edit" class="btn btn-default waves-effect waves-float waves-green"><i class="zmdi zmdi-edit"></i></a>
                                            <button type="submit" onclick="return confirm('Are you sure..?')" class="btn btn-default waves-effect waves-float waves-red"><i class="zmdi zmdi-delete"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    </div>

                    @if($data->total() > 14)
                    <div class="card">
                        <div class="body m-0">
                            {{ $data->links()  }}
                        </div>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_js')
    <script src="{{ asset('admin') }}/js/pages/tables/footable.js"></script><!-- Custom Js -->
@endsection