routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'WebsiteController@index')->name('shop');
Route::get('/artisan-register', 'WebsiteController@artisanRegister')->name('artisan.register');
Route::post('/artisan-request', 'WebsiteController@artisanRequest')->name('artisan.request');

Route::group(['prefix' => 'shop'], function () {
//    Route::get('/man', 'WebsiteController@shopMan')->name('shop.man');
//    Route::get('/woman', 'WebsiteController@shopWoman')->name('shop.woman');
//    Route::get('/woman/accessories', 'WebsiteController@shopProduct')->name('shop.products');

//    Route::get('/woman/product/detail', 'WebsiteController@shopProductDetail')->name('shop.products.detail');
    Route::get('/artisans', 'WebsiteController@shopArtisans')->name('shop.artisans');
    Route::get('/artisans/{slug}', 'WebsiteController@shopArtisansSingle')->name('shop.artisans.single');
    Route::get('/cart', 'WebsiteController@shopCart')->name('shop.cart');
    Route::get('/wish-list', 'WebsiteController@shopWish')->name('shop.wish');
    Route::get('/wishlist/{slug}','WebsiteController@storeWishList')->name('wishlist');
    Route::post('/wishlist-destroy/{id}','WebsiteController@wishListDestroy')->name('destroy');
    Route::get('/about', 'WebsiteController@shopAbout')->name('shop.about');


Route::group(['middleware' => ['auth:web']], function () { 
    Route::get('/checkout', 'WebsiteController@checkout')->name('shop.checkout');
    Route::post('/store-payment', 'PaymentController@paymentStore')->name('store.payment');

});
    // Front Dynamic Route
    Route::get('/{catName}/product/{slug}', 'WebsiteController@productDetails')->name('shop.products.detail');
    Route::get('/{slug}', 'WebsiteController@categoryShop')->name('category.shop');
    Route::get('/{cateName}/{slug}', 'WebsiteController@subcategoryShop');



//    Route::get('/product/{slug}', 'WebsiteController@shopProductDetail');
});


Route::group(['prefix' => 'cart'], function () {
    Route::post('/add/{slug}', 'WebsiteController@addToCart')->name('addToCart');
    Route::post('/update', 'WebsiteController@updateCart')->name('update.cart');
    Route::get('/remove/{id}', 'WebsiteController@removeCart')->name('remove.cart');
    Route::get('/destroy', 'WebsiteController@destroyCart')->name('destroy.cart');

    Route::post('/apply-coupon', 'WebsiteController@applyCoupon')->name('apply.coupon');

});

Route::group(['prefix' => 'user'], function () {
    Route::get('/login', 'WebsiteController@loginPage')->name('user.login.page');
    Route::get('/reset-passwod', 'WebsiteController@resetPage')->name('user.reset');
    Route::get('/customer-support', 'WebsiteController@customerSupport')->name('user.support');
    Route::get('/account', 'WebsiteController@user_accounts')->name('user.accounts.dashboard');

    Route::get('/order', 'WebsiteController@user_order')->name('user.accounts.order');
    Route::get('/order-view/{id}', 'WebsiteController@user_order_view')->name('user.accounts.order.view');

    Route::get('/address', 'WebsiteController@user_address')->name('user.accounts.address');
    Route::get('/accounts-detail', 'WebsiteController@user_details')->name('user.accounts.details');

    Route::post('/user-update/{id}', 'WebsiteController@userUpdate')->name('user.update');
    
    Route::get('/billing-address', 'WebsiteController@user_billing')->name('user.accounts.billing');
    Route::get('/shipping-address', 'WebsiteController@user_shipping')->name('user.accounts.shipping');

    // For Billing Address Routes
    Route::post('/store-billing', 'BillingController@store')->name('store.billing');

    // For shipping Address Routes
    Route::post('/store-shipping', 'ShippingController@store')->name('store.shipping');
});

Route::group(['prefix' => 'legal-area'], function () {
    Route::get('/privacy-policy', 'WebsiteController@privacyPolicy')->name('extra.privacy');
    Route::get('/work-with-us', 'WebsiteController@workWithUs')->name('extra.work');
    Route::get('/terms-and-condition', 'WebsiteController@termsAndConditoin')->name('extra.terms');
    Route::get('/faqs', 'WebsiteController@faqs')->name('extra.faqs');

});

// admin route area
Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'Auth\AdminLogin@showLoginForm');
    Route::post('/login', 'Auth\AdminLogin@login')->name('admin.login');
    Route::post('/cat-wise-subcat/{id}', 'Admin\ProductController@categoryWiseSubcategory');
    Route::get('/product-image/delete/{id}', 'Admin\ProductController@imageDelete');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::post('/logout', 'Auth\AdminLogin@logout')->name('admin.logout');

        Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');

        // for material
        Route::resource('material', 'Admin\MaterialController');
        // for category
        Route::resource('category', 'Admin\CategoryController');
        // for subcategory
        Route::resource('subcategory', 'Admin\SubcategoryController');

        // For Admin Routes
        Route::post('reset-password/{id}', 'Admin\AdminController@resetPassword');
        Route::get('artisan-request', 'Admin\AdminController@artisanRequest')->name('artisan-request');
        Route::get('artisan-accept/{id}', 'Admin\AdminController@artisanAccept');
        Route::get('artisan-reject/{id}', 'Admin\AdminController@artisanReject');
        Route::get('artisan-pending/{id}', 'Admin\AdminController@artisanPending');
        Route::resource('administrator', 'Admin\AdminController');

        // For product Routes
        Route::resource('product', 'Admin\ProductController');

        // For Team Routes
        Route::resource('team', 'Admin\TeamController');

        // For Home Banner Routes
        Route::resource('home-banner', 'Admin\HomeBannerController');

        // For Home Video Routes
        Route::resource('home-video', 'Admin\HomeVideoController');

        // For About Routes
        Route::resource('about', 'Admin\AboutController');

        // For Follow US Routes
        Route::resource('follow-us', 'Admin\FollowUsController');

        // For FAQS Routes
        Route::resource('faq', 'Admin\FaqsController');

        // For Customer Support Routes
        Route::resource('customer-support', 'Admin\CustomerSupportController');

        // For Footer Info Routes
        Route::resource('footer-info', 'Admin\FooterInfoController');

        // For Admin wishlist Routes
        Route::resource('wishlist', 'Admin\WishlistController');

        // For Admin Coupon Routes
        Route::resource('coupon', 'Admin\CouponController');

         // For Admin Order list Routes
         Route::resource('order', 'Admin\OrderController');

        
    });
   

    
    Route::post('/customer-support', 'Admin\CustomerSupportController@store')->name('customer.support');
});

//Route::get('/home', 'HomeController@index')->name('home');
 

resources/views/admin/includes/_subcategory.blade.php
@if(!empty($subcategories))
    <option>-- Select Subcategory --</option>
    @foreach($subcategories as $subcategory)
        <option value="{!! $subcategory->id !!}">{!! $subcategory->title !!}</option>
    @endforeach
@else
    <option>- Subcategory Not found -</option>
@endif

resources/views/admin/includes/header.blade.php
<nav class="navbar">
    <div class="col-12">
        <div class="navbar-header bg-blue-grey">
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="index.html"><img src="{{ asset('admin') }}/logo-mark.svg" width="30" alt="Compass"><span class="m-l-10">Barròco</span></a>
        </div>
        <ul class="nav navbar-nav navbar-left">
            <li><a href="javascript:void(0);" class="ls-toggle-btn" data-close="true"><i class="zmdi zmdi-swap"></i></a></li>
            <li class="hidden-sm-down">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-addon">
                        <i class="zmdi zmdi-search"></i>
                    </span>
                </div>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button"><i class="zmdi zmdi-notifications"></i>
                    <div class="notify"><span class="heartbit"></span><span class="point"></span></div>
                </a>
                <ul class="dropdown-menu dropdown-menu-right slideDown">
                    <li class="header">NOTIFICATIONS</li>
                    <li class="body">
                        <ul class="menu list-unstyled">
                            <li> <a href="javascript:void(0);">
                                    <div class="icon-circle bg-blue"><i class="zmdi zmdi-account"></i></div>
                                    <div class="menu-info">
                                        <h4>8 New Members joined</h4>
                                        <p><i class="zmdi zmdi-time"></i> 14 mins ago </p>
                                    </div>
                                </a> </li>
                            <li> <a href="javascript:void(0);">
                                    <div class="icon-circle bg-amber"><i class="zmdi zmdi-shopping-cart"></i></div>
                                    <div class="menu-info">
                                        <h4>4 Sales made</h4>
                                        <p> <i class="zmdi zmdi-time"></i> 22 mins ago </p>
                                    </div>
                                </a> </li>
                            <li> <a href="javascript:void(0);">
                                    <div class="icon-circle bg-red"><i class="zmdi zmdi-delete"></i></div>
                                    <div class="menu-info">
                                        <h4><b>Nancy Doe</b> Deleted account</h4>
                                        <p> <i class="zmdi zmdi-time"></i> 3 hours ago </p>
                                    </div>
                                </a> </li>
                            <li> <a href="javascript:void(0);">
                                    <div class="icon-circle bg-green"><i class="zmdi zmdi-edit"></i></div>
                                    <div class="menu-info">
                                        <h4><b>Nancy</b> Changed name</h4>
                                        <p> <i class="zmdi zmdi-time"></i> 2 hours ago </p>
                                    </div>
                                </a> </li>
                            <li> <a href="javascript:void(0);">
                                    <div class="icon-circle bg-grey"><i class="zmdi zmdi-comment-text"></i></div>
                                    <div class="menu-info">
                                        <h4><b>John</b> Commented your post</h4>
                                        <p> <i class="zmdi zmdi-time"></i> 4 hours ago </p>
                                    </div>
                                </a> </li>
                            <li> <a href="javascript:void(0);">
                                    <div class="icon-circle bg-purple"><i class="zmdi zmdi-refresh"></i></div>
                                    <div class="menu-info">
                                        <h4><b>John</b> Updated status</h4>
                                        <p> <i class="zmdi zmdi-time"></i> 3 hours ago </p>
                                    </div>
                                </a> </li>
                            <li> <a href="javascript:void(0);">
                                    <div class="icon-circle bg-light-blue"><i class="zmdi zmdi-settings"></i></div>
                                    <div class="menu-info">
                                        <h4>Settings Updated</h4>
                                        <p> <i class="zmdi zmdi-time"></i> Yesterday </p>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="footer"> <a href="javascript:void(0);">View All Notifications</a> </li>
                </ul>
            </li>

            <li>
                <a href="javascript:void(0);" class="fullscreen hidden-sm-down" data-provide="fullscreen" data-close="true"><i class="zmdi zmdi-fullscreen"></i></a>
            </li>
            <li><a href="{{ route('admin.logout') }}"onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="mega-menu" data-close="true"><i class="zmdi zmdi-power"></i></a></li>
            <form id="logout-form" action="{!! url('admin/logout') !!}" method="POST" style="display: none;">
                @csrf
            </form>
            <li class=""><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="zmdi zmdi-settings zmdi-hc-spin"></i></a></li>
        </ul>
    </div>
</nav>

resources/views/admin/includes/navbar.blade.php
<aside id="leftsidebar" class="sidebar">
    <div class="menu">
        <ul class="list">
            <li>
                <div class="user-info">
                    <div class="image">
                        <a href="#">
                            @if( auth()->guard('admin')->user()->avatar)
                                <img src="{{ auth()->guard('admin')->user()->avatar }}" alt="User">
                            @else
                                <img src="{{ asset('admin') }}/avatar.png" alt="User">
                            @endif
                        </a>
                    </div>
                    <div class="detail">
                        <h4>{{ auth()->guard('admin')->user()->name }}</h4>
                        @if(auth()->guard('admin')->user()->role == 'super_admin')
                            <small>Super Admin</small>
                        @elseif(auth()->guard('admin')->user()->role == 'admin')
                            <small>Admin (Manager)</small>
                        @else
                            <small>Craftsman</small>
                        @endif
                    </div>
                    <a href="#" title="Events"><i class="zmdi zmdi-calendar"></i></a>
                    <a href="#" title="Inbox"><i class="zmdi zmdi-email"></i></a>
                    <a href="#" title="Contact List"><i class="zmdi zmdi-account-box-phone"></i></a>
                    <a href="#" title="Chat App"><i class="zmdi zmdi-comments"></i></a>
                    <a href="{{ route('admin.logout') }}"onclick="event.preventDefault(); document.getElementById('logout-form').submit();" title="Sign out"><i class="zmdi zmdi-power"></i></a>
                    <form id="logout-form" action="{!! url('admin/logout') !!}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
            <li class="header">MAIN</li>
            <li class="{{ Request::is('admin/dashboard') ? 'active':'' }}">
                <a href="{{ route('admin.dashboard') }}"><i class="zmdi zmdi-home"></i><span>Dashboard</span></a>
            </li>

            <li class="header">PRODUCTS</li>
            <li class="{{ Request::is('admin/category*') || Request::is('admin/subcategory*') || Request::is('admin/product*') || Request::is('admin/material*') || Request::is('admin/wishlist*') || Request::is('admin/order*') ? 'active open':'' }}">
                <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-shopping-cart"></i><span>Products</span> </a>
                <ul class="ml-menu">
                    <li class="{{ Request::is('admin/material*') ? 'active':'' }}"><a href="{{ route('material.index') }}">Materials</a></li>
                    <li class="{{ Request::is('admin/category*') ? 'active':'' }}"><a href="{{ route('category.index') }}">Categories</a></li>
                    <li class="{{ Request::is('admin/subcategory*') ? 'active':'' }}"><a href="{{ route('subcategory.index') }}">Sub Categories</a></li>
                    <li class="{{ Request::is('admin/product*') ? 'active':'' }}"><a href="{{ route('product.index') }}">Product</a></li>
                    <li class="{{ Request::is('admin/wishlist*') ? 'active':'' }}"><a href="{{ route('wishlist.index') }}">Wish List</a></li>
                    <li class="{{ Request::is('admin/order*') ? 'active':'' }}"><a href="{{ route('order.index') }}">Order List</a></li>
                </ul>
            </li>

            <li class="header">Admin Area</li>
            <li class="{{ Request::is('admin/administrator*') || Request::is('admin/artisan-request*')  ? 'active open':'' }}">
                <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-accounts-list"></i><span>Admin & Role</span> </a>
                <ul class="ml-menu">
                    <li class="{{ Request::is('admin/administrator*') ? 'active':'' }}"><a href="{{ route('administrator.index') }}">Administrators</a></li>
                    <li class="{{ Request::is('admin/artisan-request') ? 'active':'' }}"><a href="{{ route('artisan-request') }}">Artisan Request</a></li>
                </ul>
            </li>
            <li class="header">About Area</li>
            <li class="{{ Request::is('admin/team*') || Request::is('admin/follow-us*') || Request::is('admin/about*')  || Request::is('admin/customer-support*') ? 'active open':'' }}">
                <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-settings"></i><span>Abouts</span> </a>
                <ul class="ml-menu">
                <li class="{{ Request::is('admin/about*') ? 'active':'' }}"><a href="{{route('about.index')}}">About</a></li>
                <li class="{{ Request::is('admin/follow-us*') ? 'active':'' }}"><a href="{{route('follow-us.index')}}">Follow Us</a></li>
                <li class="{{ Request::is('admin/team*') ? 'active':'' }}"><a href="{{route('team.index')}}">Team</a></li>
                <li class="{{ Request::is('admin/customer-support*') ? 'active':'' }}"><a href="{{route('customer-support.index')}}">Customer Support</a></li>
                </ul>
            </li>

            <li class="header">Site Setting</li>
            <li class="{{ Request::is('admin/home-banner*') ||  Request::is('admin/home-video*') || Request::is('admin/faq*') || Request::is('admin/footer-info*') || Request::is('admin/coupon*') ? 'active open':'' }}">
                <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-settings"></i><span>Settings</span> </a>
                <ul class="ml-menu">
                    <li class="{{ Request::is('admin/home-banner*') ? 'active':'' }}"><a href="{{route('home-banner.index')}}">Home Banner</a></li>
                    <li class="{{ Request::is('admin/home-video*') ? 'active':'' }}"><a href="{{route('home-video.index')}}">Home Video</a></li>
                    <li class="{{ Request::is('admin/faq*') ? 'active':'' }}"><a href="{{route('faq.index')}}">FAQS</a></li>
                    <li class="{{ Request::is('admin/footer-info*') ? 'active':'' }}"><a href="{{route('footer-info.index')}}">Footer Information</a></li>
                    <li class="{{ Request::is('admin/coupon*') ? 'active':'' }}"><a href="{{route('coupon.index')}}">Coupon Code</a></li>
                </ul>

            </li>



            <!--
            <li> <a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-delicious"></i><span>Widgets</span> </a>
                <ul class="ml-menu">
                    <li><a href="widgets-app.html">Apps Widgets</a></li>
                    <li><a href="widgets-data.html">Data Widgets</a></li>
                </ul>
            </li>
            -->
        </ul>
    </div>
</aside>